### ISSUE TITLE
NPE: Cannot invoke "io.grpc.netty.NettyWritableBuffer.bytebuf()" because "frame" is null

### ISSUE THREAD

**Issue by rlubke** [micronaut-projects/micronaut-coherence#248]
### Expected Behavior

No NPE raised by runtime.

### Actual Behaviour

Attempting upgrade of `micronaut-coherence` to `3.4.0` and running `GrpcProxyTest` yields:
```
SEVERE: Caught exception handling onComplete
java.lang.NullPointerException: Cannot invoke "io.grpc.netty.NettyWritableBuffer.bytebuf()" because "frame" is null
	at io.grpc.netty.NettyServerStream$Sink.writeFrameInternal(NettyServerStream.java:111)
	at io.grpc.netty.NettyServerStream$Sink.writeFrame(NettyServerStream.java:133)
	at io.grpc.internal.AbstractServerStream.deliverFrame(AbstractServerStream.java:111)
	at io.grpc.internal.MessageFramer.commitToSink(MessageFramer.java:350)
	at io.grpc.internal.MessageFramer.close(MessageFramer.java:326)
	at io.grpc.internal.AbstractStream.endOfMessages(AbstractStream.java:84)
	at io.grpc.internal.AbstractServerStream.close(AbstractServerStream.java:120)
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:223)
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:207)
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39)
	at com.oracle.coherence.grpc.proxy.GrpcMetricsInterceptor$ResponseCountingServerCall.close(GrpcMetricsInterceptor.java:146)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:395)
	at com.oracle.coherence.grpc.SafeStreamObserver.onCompleted(SafeStreamObserver.java:98)
	at com.oracle.coherence.grpc.proxy.NamedCacheServiceGrpcImpl.handleUnary(NamedCacheServiceGrpcImpl.java:304)
	at com.oracle.coherence.grpc.proxy.NamedCacheServiceGrpcImpl.lambda$put$10(NamedCacheServiceGrpcImpl.java:221)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Steps To Reproduce

Update libs.versions.toml `micronaut-grpc` version to `3.4.0` run tests in `coherence-grpc-test`.

### Version

3.7.3

**Comment by rlubke** [comment]
Fixed by: https://github.com/micronaut-projects/micronaut-coherence/commit/c610a09c005c69a7c047806a2753ee7e8adec19b
